### ISSUE TITLE
ssl issue with demo

### ISSUE THREAD

**Issue by juni-vogt** [salsita/jq-clipthru#1]
The demo doesn't work right now because of SSL issues.
Pls load
http://fonts.googleapis.com/css?family=Press+Start+2P and
http://code.jquery.com/jquery-1.11.0.min.js
with `//` instead of `http://` for auto ssl detection.

**Comment by ghost** [comment]
Hi @matthias-vogt,

Thanks for the report, I'll get to change that soon hopefully. In the meantime, you can just use `http`. There is nothing that would need a security layer on the demo page.

**Comment by juni-vogt** [comment]
I tried, but Github pages doesn't let you :p

**Comment by ghost** [comment]
@matthias-vogt Sure it allows both, I'm doing it right now. Check if you have any plugins like `https-everywhere` enabled. http://salsita.github.io/jq-clipthru/demo/ should lead straight to the page.

**Comment by juni-vogt** [comment]
Sorry, my bad. You're right, it was because of https-everywhere.

**Comment by ghost** [comment]
No problem, I will change the requests in any case. Thanks again for the report.

**Comment by ghost** [comment]
Fixed after 2 years of absolute negligence. Sorry.
