### ISSUE TITLE
e.widget is not a function error when loading script

### ISSUE THREAD

**Issue by thdoan** [salsita/jq-clipthru#2]
I get the following error when loading the script:

"Uncaught TypeError: e.widget is not a function"

Here is my code:

```
<!--[if lt IE 9]>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<![endif]-->
<!--[if IE 9]><!-->
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<!--<![endif]-->
<script src="http://cdn.rawgit.com/salsita/jq-clipthru/3818c723/build/jq-clipthru.min.js"></script>
```

**Comment by thdoan** [comment]
Never mind -- I realized jquery-ui-1.10.4.custom.min.js is also required.

**Comment by ghost** [comment]
Hello @thdoan, jQuery UI widget factory is unfortunately still required. It is possible that I will get to rewrite this library soon into something more modern with native code.
