### ISSUE TITLE
Jq-clipthru and dynamically added elements

### ISSUE THREAD

**Issue by bhairava3** [salsita/jq-clipthru#6]
Hello! Wonderful plugin, thanks for that! But tell me, please, how to activate it for dynamically added elements? Unfortunately, after adding a dynamic element and calling the plugin a second time, nothing works.

**Comment by ghost** [comment]
Hello @bhairava3, do you perhaps have a code sample of the issue somewhere? If you call the plugin again where the selector contains your new elements, it should work.
